name: Run Market Data Updates

on:
  schedule:
      - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install Dependencies
        run: |
          pipenv install --dev
          pipenv run pip freeze > requirements.txt

      - name: Generate .py files
        working-directory: reference_data/market_data
        run: pipenv run jupyter nbconvert --to python get_market_data.ipynb
                  
      - name: Run py
        working-directory: reference_data/market_data
        run: |
          max_attempts=3
          attempt=1
          success=false
          
          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt of $max_attempts:"
            if pipenv run python get_market_data.py; then
              success=true
              break
            else
              echo "Attempt $attempt failed. Retrying..."
              attempt=$((attempt+1))
              sleep 5
            fi
          done
          if [ "$success" = false ]; then
            echo "All attempts failed."
            exit 1
          fi
        env:
          L1_ETHERSCAN_API: ${{ secrets.L1_ETHERSCAN_API }}

      # Rest of your workflow remains the same
      # ...
