name: Python Package Installation

on:
  push:
    branches: [ main ]  # Adjust this if your main branch has a different name
  pull_request:
    branches: [ main ]  # Adjust this if your main branch has a different name
  workflow_dispatch:  # This allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11

    - name: Install Pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv

    - name: Install dependencies from lock file
      run: pipenv sync --dev

    - name: If lock file install fails, update and retry
      if: failure()
      run: |
        pipenv lock
        pipenv sync --dev

    - name: Show installed packages
      run: pipenv graph
